json.talent @talent
json.next_aventure @next_aventure
json.experiences @experiences
json.formations @formations
json.knowns @knowns
json.mobilities @mobilities
json.skills @skills
json.sector_ids @sector_ids
json.sectors @sectors
json.technos @technos
json.talent_languages @talent_languages
json.job @job
json.second_job @second_job
json.jobs @jobs